<?php

/**
 * Plugin Name: Lorem
 * Author: Hervé Inisan
 * Version: 1.0
 * Description: A lorem plugin
 */
add_shortcode('lorem', 'shortcode_lorem');

function shortcode_lorem($userAttributes)
{
    $defaultAttributes = ["words" => 25];

    $wordlist = [
        "ac",
        "accumsan",
        "adipiscing",
        "aliquam",
        "aliquet",
        "amet",
        "ante",
        "arcu",
        "at",
        "auctor",
        "augue",
        "bibendum",
        "blandit",
        "commodo",
        "condimentum",
        "congue",
        "consectetur",
        "consequat",
        "convallis",
        "cras",
        "curabitur",
        "cursus",
        "dapibus",
        "diam",
        "dictum",
        "dictumst",
        "dignissim",
        "dis",
        "dolor",
        "donec",
        "dui",
        "duis",
        "efficitur",
        "egestas",
        "eget",
        "eleifend",
        "elit",
        "enim",
        "erat",
        "eros",
        "et",
        "etiam",
        "eu",
        "euismod",
        "ex",
        "facilisis",
        "faucibus",
        "felis",
        "feugiat",
        "finibus",
        "gravida",
        "habitasse",
        "hac",
        "hendrerit",
        "iaculis",
        "id",
        "in",
        "integer",
        "interdum",
        "ipsum",
        "justo",
        "lacinia",
        "lacus",
        "laoreet",
        "lectus",
        "leo",
        "libero",
        "ligula",
        "lorem",
        "maecenas",
        "magna",
        "magnis",
        "malesuada",
        "massa",
        "mauris",
        "maximus",
        "metus",
        "mi",
        "molestie",
        "mollis",
        "montes",
        "mus",
        "nam",
        "nascetur",
        "natoque",
        "nec",
        "neque",
        "nisi",
        "nisl",
        "non",
        "nulla",
        "nunc",
        "odio",
        "orci",
        "ornare",
        "parturient",
        "pellentesque",
        "penatibus",
        "pharetra",
        "placerat",
        "platea",
        "porta",
        "porttitor",
        "posuere",
        "praesent",
        "pretium",
        "pulvinar",
        "purus",
        "quam",
        "quis",
        "quisque",
        "ridiculus",
        "risus",
        "rutrum",
        "sapien",
        "scelerisque",
        "sed",
        "sem",
        "sit",
        "sodales",
        "sollicitudin",
        "suscipit",
        "suspendisse",
        "tellus",
        "tempor",
        "tincidunt",
        "tortor",
        "tristique",
        "turpis",
        "ultrices",
        "ultricies",
        "urna",
        "ut",
        "varius",
        "vel",
        "velit",
        "venenatis",
        "vestibulum",
        "vitae",
        "viverra",
        "volutpat",
        "vulputate",
    ];


    $finalAttributes = shortcode_atts($defaultAttributes, $userAttributes);

    extract($finalAttributes);

    $text = "";

    // for ($i = 0; $i < $words; $i++) {
    //     $text = $text . $wordlist[rand(0, count($wordlist))] . " ";
    // }

    return $text;
}
